image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Dependencies
    init: |
      npm ci
      npm install cypress --save-dev
  - name: Run Cypress Tests
    command: npx cypress run --headed

vscode:
  extensions:
    - dsznajder.es7-react-js-snippets
    - eamodio.gitlens
    - ms-azuretools.vscode-docker

ports:
  - port: 3000
    onOpen: open-preview

# github:
#   prebuilds:
#     - branches: "*"